clc;
clear;
close all;

%% ============================================================
%     SHANNON-FANO COMPRESSED TEXT TRANSMISSION
%     TRANSMITTER + RECEIVER
% =============================================================

%% ===================== TRANSMITTER ===========================

tx = figure('Name','TRANSMITTER',...
    'NumberTitle','off',...
    'Position',[100 100 750 650],...
    'Color',[0.94 0.94 0.94]);

uicontrol(tx,'Style','text',...
    'String','SHANNON-FANO TRANSMITTER',...
    'FontSize',20,...
    'FontWeight','bold',...
    'Position',[150 590 450 40],...
    'BackgroundColor',[0.94 0.94 0.94]);

% Input text
uicontrol(tx,'Style','text',...
    'String','Enter Text:',...
    'FontSize',13,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'Position',[50 545 150 30],...
    'BackgroundColor',[0.94 0.94 0.94]);

inputBox = uicontrol(tx,...
    'Style','edit',...
    'String','HELLO SHANNON FANO',...
    'FontSize',12,...
    'Position',[50 500 650 45]);

% Button
uicontrol(tx,...
    'Style','pushbutton',...
    'String','COMPRESS AND TRANSMIT',...
    'FontSize',13,...
    'FontWeight','bold',...
    'Position',[225 440 300 45],...
    'Callback',@(src,event) compressText(inputBox));

% Code table
uicontrol(tx,...
    'Style','text',...
    'String','SHANNON-FANO CODE TABLE',...
    'FontSize',13,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'Position',[50 395 350 30],...
    'BackgroundColor',[0.94 0.94 0.94]);

tableBox = uicontrol(tx,...
    'Style','listbox',...
    'FontSize',11,...
    'Position',[50 230 650 165]);

% Compressed text
uicontrol(tx,...
    'Style','text',...
    'String','COMPRESSED TEXT (BINARY)',...
    'FontSize',13,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'Position',[50 195 350 30],...
    'BackgroundColor',[0.94 0.94 0.94]);

compressedBox = uicontrol(tx,...
    'Style','edit',...
    'Max',10,...
    'Min',0,...
    'Enable','inactive',...
    'HorizontalAlignment','left',...
    'FontSize',10,...
    'Position',[50 80 650 115]);

% Statistics
statsBox = uicontrol(tx,...
    'Style','text',...
    'String','Compression information will appear here.',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'Position',[50 25 650 45],...
    'BackgroundColor',[0.94 0.94 0.94]);


%% ============================================================
%                  COMPRESSION FUNCTION
% =============================================================

function compressText(inputBox)

    % Get input text
    originalText = get(inputBox,'String');

    if isempty(originalText)
        errordlg('Please enter some text!');
        return;
    end

    %% Character frequency

    characters = unique(originalText);

    frequency = zeros(1,length(characters));

    for i = 1:length(characters)
        frequency(i) = sum(originalText == characters(i));
    end

    %% Sort frequency

    [frequency,index] = sort(frequency,'descend');

    characters = characters(index);

    %% Generate Shannon-Fano codes

    codes = cell(1,length(characters));

    for i = 1:length(characters)
        codes{i} = '';
    end

    if length(characters) == 1

        codes{1} = '0';

    else

        codes = shannonFano(...
            frequency,...
            codes,...
            1:length(characters));

    end

    %% Display code table

    tableBox = findobj(gcf,'Style','listbox');

    displayData = {};

    for i = 1:length(characters)

        if characters(i) == ' '
            symbol = '[SPACE]';
        else
            symbol = characters(i);
        end

        displayData{end+1} = sprintf(...
            '%-10s Frequency = %-3d   Code = %s',...
            symbol,...
            frequency(i),...
            codes{i});

    end

    set(tableBox,'String',displayData);

    %% ========================================================
    %                    COMPRESS TEXT
    % =========================================================

    compressedText = '';

    for i = 1:length(originalText)

        position = find(...
            characters == originalText(i),...
            1);

        compressedText = [...
            compressedText codes{position}];

    end

    %% Display compressed text

    compressedBox = findobj(...
        gcf,...
        'Style','edit',...
        '-and',...
        'Enable','inactive');

    set(compressedBox,'String',compressedText);

    %% ========================================================
    %                 COMPRESSION STATISTICS
    % =========================================================

    originalBits = length(originalText) * 8;

    compressedBits = length(compressedText);

    compressionRatio = ...
        originalBits / compressedBits;

    spaceSaved = ...
        ((originalBits-compressedBits) / originalBits) * 100;

    statsBox = findobj(...
        gcf,...
        'Style','text');

    information = sprintf(...
        'Original Size: %d bits     Compressed Size: %d bits     Compression Ratio: %.2f : 1     Space Saved: %.2f %%',...
        originalBits,...
        compressedBits,...
        compressionRatio,...
        spaceSaved);

    set(statsBox(end),'String',information);

    %% ========================================================
    %                     OPEN RECEIVER
    % =========================================================

    createReceiver(...
        originalText,...
        characters,...
        codes,...
        compressedText);

end


%% ============================================================
%                  SHANNON-FANO ALGORITHM
% =============================================================

function codes = shannonFano(frequency,codes,index)

    if length(index) <= 1
        return;
    end

    total = sum(frequency(index));

    cumulative = 0;

    minimumDifference = inf;

    splitPoint = 1;

    for i = 1:length(index)-1

        cumulative = ...
            cumulative + frequency(index(i));

        remaining = total - cumulative;

        difference = ...
            abs(cumulative-remaining);

        if difference < minimumDifference

            minimumDifference = difference;

            splitPoint = i;

        end

    end

    group1 = index(1:splitPoint);

    group2 = index(splitPoint+1:end);

    % First group = 0

    for i = group1
        codes{i} = [codes{i} '0'];
    end

    % Second group = 1

    for i = group2
        codes{i} = [codes{i} '1'];
    end

    % Recursive division

    codes = shannonFano(...
        frequency,...
        codes,...
        group1);

    codes = shannonFano(...
        frequency,...
        codes,...
        group2);

end


%% ============================================================
%                    RECEIVER FUNCTION
% =============================================================

function createReceiver(...
    originalText,...
    characters,...
    codes,...
    compressedText)

    rx = figure(...
        'Name','RECEIVER',...
        'NumberTitle','off',...
        'Position',[900 100 750 650],...
        'Color',[0.94 0.94 0.94]);

    %% Title

    uicontrol(rx,...
        'Style','text',...
        'String','SHANNON-FANO RECEIVER',...
        'FontSize',20,...
        'FontWeight','bold',...
        'Position',[150 590 450 40],...
        'BackgroundColor',[0.94 0.94 0.94]);

    %% Received compressed data

    uicontrol(rx,...
        'Style','text',...
        'String','RECEIVED COMPRESSED TEXT:',...
        'FontSize',13,...
        'FontWeight','bold',...
        'HorizontalAlignment','left',...
        'Position',[50 545 400 30],...
        'BackgroundColor',[0.94 0.94 0.94]);

    uicontrol(rx,...
        'Style','edit',...
        'String',compressedText,...
        'Max',10,...
        'Min',0,...
        'Enable','inactive',...
        'HorizontalAlignment','left',...
        'FontSize',10,...
        'Position',[50 420 650 120]);

    %% Code table

    uicontrol(rx,...
        'Style','text',...
        'String','SHANNON-FANO CODE TABLE',...
        'FontSize',13,...
        'FontWeight','bold',...
        'HorizontalAlignment','left',...
        'Position',[50 385 350 30],...
        'BackgroundColor',[0.94 0.94 0.94]);

    codeTable = {};

    for i = 1:length(characters)

        if characters(i) == ' '
            symbol = '[SPACE]';
        else
            symbol = characters(i);
        end

        codeTable{end+1} = sprintf(...
            '%-10s Code = %s',...
            symbol,...
            codes{i});

    end

    uicontrol(rx,...
        'Style','listbox',...
        'String',codeTable,...
        'FontSize',11,...
        'Position',[50 275 650 110]);

    %% Decompress button

    uicontrol(rx,...
        'Style','pushbutton',...
        'String','DECOMPRESS / RECEIVE',...
        'FontSize',13,...
        'FontWeight','bold',...
        'Position',[225 215 300 45],...
        'Callback',@(src,event) decodeText(...
        originalText,...
        characters,...
        codes,...
        compressedText,...
        rx));

    %% Output heading

    uicontrol(rx,...
        'Style','text',...
        'String','DECOMPRESSED / RECEIVED TEXT:',...
        'FontSize',13,...
        'FontWeight','bold',...
        'HorizontalAlignment','left',...
        'Position',[50 175 400 30],...
        'BackgroundColor',[0.94 0.94 0.94]);

    %% Output box

    outputBox = uicontrol(rx,...
        'Style','edit',...
        'String','Press DECOMPRESS / RECEIVE',...
        'FontSize',12,...
        'Max',5,...
        'Min',0,...
        'Enable','inactive',...
        'HorizontalAlignment','left',...
        'Position',[50 90 650 80]);

    %% Status

    statusBox = uicontrol(rx,...
        'Style','text',...
        'String','STATUS: Waiting for transmission...',...
        'FontSize',12,...
        'FontWeight','bold',...
        'Position',[50 35 650 40],...
        'BackgroundColor',[0.94 0.94 0.94]);


    %% ========================================================
    %                     DECODE FUNCTION
    % =========================================================

    function decodeText(...
        originalText,...
        characters,...
        codes,...
        compressedText,...
        rx)

        decodedText = '';

        currentCode = '';

        %% Decode binary data

        for k = 1:length(compressedText)

            currentCode = ...
                [currentCode compressedText(k)];

            for j = 1:length(codes)

                if strcmp(...
                        currentCode,...
                        codes{j})

                    decodedText = ...
                        [decodedText characters(j)];

                    currentCode = '';

                    break;

                end

            end

        end

        %% Find output box

        editBoxes = findobj(...
            rx,...
            'Style','edit');

        outputBox = editBoxes(1);

        %% Display decoded text

        set(outputBox,...
            'String',decodedText);

        %% Find status box

        textObjects = findobj(...
          rx,...
            'Style','text');

        statusBox = textObjects(1);

        %% Check transmission

        if strcmp(decodedText,originalText)

            set(statusBox,...
                'String',...
                'STATUS: TRANSMISSION SUCCESSFUL');

        else

            set(statusBox,...
                'String',...
                'STATUS: TRANSMISSION ERROR');

        end

    end
end 
